nodes:
  - id: 1
    host: localhost
    port: 3333
  - id: 2
    host: localhost
    port: 3334
  - id: 3
    host: localhost
    port: 3335

myid: 1
logSync: true
syncInterval: 1000
useMembership: false
